### ISSUE TITLE
The line login = input(str("Please enter the password for " + l_n + " Username: ")) does not work in the boot sequance.

### ISSUE THREAD

**Issue by MicklePickl** [LucaBarbaLata/Rudolf-OS#1] opened 2023-12-22 18:55 UTC

**Comment by LucaBarbaLata** [comment] 2024-06-09 10:47
hello. i am now seeing this issue. i am working on a fix rn. sorry for any inconvenience created

**Comment by LucaBarbaLata** [comment] 2024-06-09 10:58
The issue is now fixed. Please create a folder with the name "user" alongside with the other files for the program to work

**Closed by LucaBarbaLata** 2024-06-09 10:58 UTC
Labels: bug
